# Generated by Django 3.2.7 on 2025-02-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cartorder_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='life',
            field=models.CharField(blank=True, default='100 Days', max_length=500000, null=True),
        ),
    ]
